version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build: ./server
    container_name: backend-server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongo:27017/webchat
    depends_on:
      - mongo
  client:
    build: ./client
    container_name: frontend-client
    ports: 
      - "3000:80"
    depends_on: 
      - mongo
      - backend
volumes:
  mongo-data: